version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "20:00" # UTC 时间
    commit-message:
      prefix: "[github-actions] "

